apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: websocket-app-timeout
  namespace: demo-app
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: websocket-app
  timeout:
    tcp:
      connectTimeout: 5s
    http:
      requestTimeout: 3600s
