apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: api-gateway-rate-limit
  namespace: demo-app
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: api-gateway
  rateLimit:
    type: Local
    local:
      rules:
        - limit:
            requests: 100
            unit: Second
